apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-lab
  template:
    metadata:
      labels:
        app: otus-lab
    spec:
      containers:
        - name: otus-lab
          image: bl00dhound/otus_lab:v2
          env:
            - name: CNFG_DB__CONNECTION__HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CNFG_DB__CONNECTION__HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
